### PR TITLE
404 error for total miss

### PR DESCRIPTION
**Pull request by YaphetKG**

### CODE REVIEW

**Comment by patrickkwang** [comment]
In the interest of maintaining readability, we should establish a consistent coding style. There are at least three issues this very small change raises:

1. Prefer single- our double-quoted strings? I seem to lean toward single quotes.
2. Test list empty using `if not x`? This is the most popular approach.
3. New lines at the end of error responses? Is there a reason for this?

Any ideas/preferences?

**Comment by patrickkwang** [comment]
On a less debatable note, this should definitely not be an f-string unless we're formatting something.

**Comment by YaphetKG** [comment]
I agree with all the points, I've updated it as such

**Review by patrickkwang — APPROVED** [review]
👍

**Pull request merged**
